name: Slack notification on job failure
on: push
jobs:
  slack-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Fail job
        run: exit 1
      - name: Slack notification
        if: failure()
        uses: rtCamp/action-slack-notify@c753c78497b021971cf6540efe8c3a131e4b702f
        env:
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
