name: Security Audit
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node.js 18
        uses: actions/setup-node@v1.3.0
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Audit
        run: npm audit